version: 2.1

orbs:
  slack: circleci/slack@4.12.0

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  check_backend:
    type: boolean
    default: false
  check_frontend:
    type: boolean
    default: false

jobs:
  say-backend:
    docker:
      - image: cimg/base:stable
      - image: cimg/python:3.10.9

    steps:
      - checkout
      - run:
          name: "Say hello backend"
          command: "echo <<pipeline.parameters.check_backend>>"
      - run:
          name: Installing Dependencies
          command: |
            cd backend/
            python3.10 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Migrate DB
          command: |
            cd backend/
            . venv/bin/activate
            python manage.py migrate
      - run:
          name: Running Tests
          command: |
            cd backend/
            . venv/bin/activate
            python manage.py test

  say-frontend:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello frontend"
          command: "echo <<pipeline.parameters.check_frontend>>"
  
  
  
# here we specify our workflows, most of which are conditionally
# executed based upon pipeline parameter values. Each workflow calls a
# specific job defined above, in the jobs section.
workflows:
  # when pipeline parameter, run-build-service-1-job is true, the
  # build-service-1 job is triggered.
  TEST_BACKEND:
    jobs:
      - say-backend
  Test_FRONTEND:
    when: <<pipeline.parameters.check_frontend>>
    jobs:
      - say-frontend
 